version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
      - ./config:/app/config:ro
    env_file:
      - .env
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - DOCKER=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
