version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./config:/app/config
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=UTC
