version: '3.8'

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: binance_bot
    user: "${UID:-1000}:${GID:-1000}"  # Use host user's UID/GID
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw
      - ./config:/app/config:ro
    env_file:
      - .env
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - DOCKER=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
