version: '3.8'

services:
  binance-bot:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_USER: ${APP_USER:-botuser}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: binance-bot
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
    environment:
      - TZ=${TZ:-UTC}
      - UMASK=${UMASK:-0027}
      - DOCKER=true
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-512M}
          cpus: ${CPU_LIMIT:-0.5}
    healthcheck:
      test: ["CMD", "python", "-c", "import sys, os; sys.exit(0 if os.path.exists('/app/data/trades.json') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
        compress: "true"
